disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - force_cast
  - identifier_name
  - function_parameter_count
  - type_body_length
  # <---------
opt_in_rules: # some rules are only opt-in
  - empty_count
